### ISSUE TITLE
Use the branch name as base version - switch to Git Flow

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#158]
This would impact the CI jobs by forcing to release from a branch instead of from the master.

~~Time to switch to Git Flow!~~ No! The Git Flow is not compatible with having maintenance branches. The flow is similar to the one used by Atlassian:
- feature branches around the `master` branch
- creation of `release/*` branches for the versions to maintain
- [x] ~~Create the `develop` branch~~
- [x] Adapt the _versioning.gradle_ code to the new situation
- [x] Adapt the CD jobs to work with branches
- [x] Branch normalisation in Ontrack (#161)
- [x] CD jobs to notify Ontrack
- [x] Release job for any branch - see also #164
- [x] Release shell in the `delivery` package #162 
- [x] **Ontrack build <-> Git commit using commits** (when there is no tag) #163 
- [x] Merge the `feature/158-git-flow` into the `develop` branch
- [x] Create the `2.0` branch from `master`
- [x] Release from the `2.0` branch - see #63 
- [x] Deploy a first release 2.0 in Ontrack and redo a release in order to validate the release process
- [x] ~~The `version.base` for a tag must be `master` (or the associated branch)~~
- [x] ~~Create `release` task in the publication to merge into and tag the `master` branch, and reintegrate into the `develop` branch - see #63~~
- [x] ~~`master` becomes the _production_ branch upon release of the `2.0-abddef` by merging the 2.0 branch into it - see #63~~
- [x] ~~Pre-merge test for feature branches~~ - see #165 
- [x] Regression with templating - see #166 
- [x] Check that the released application is suitable for production
- [x] Auto increment of the display version (`release/2.0` --> `2.0.0`, then `2.0.1` etc.)
