### ISSUE TITLE
Meta information property and decoration for entities

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#278]
Being able to attach a set of meta information to any entity.

Meta information is a list of:

* name
* value
* link

The property will display the list of meta information using:

* name --> value, and a link on the value

The decoration will display:

* name --> value, and be a link itself

Actions:

* [x] Property
* [x] Decoration
* [x] DSL to specify the property + add a meta information

* [x] One must be able to query on the meta information in the filters

> It is already possible, but the syntax for the search must `name:value`

* [x] One must be able to query on the meta information, in the project search

> Add a property criteria in the _Advanced_ section of the search form

* [x] The global query will be also available: see #280
