### ISSUE TITLE
At validation run and build level, store information about CI

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#600]
Builds and validation runs can be associated with the following data:

* source type (i.e. "jenkins")
* source uri (i.e. build URL)
* execution trigger (i.e. "scm" or user)
* execution time
* ~execution quality (total tests + failed tests)~ #176 

Display this data in the general branch overview and in the build / validation run page.

Implementation node: new table, linked to builds or validation run, optional fields.

- [x] Table and model
- [x] Model: signature
- [x] Getting the run info
- [x] Setting the run info
- [x] Deleting the run info
- [x] GraphQL: build
- [x] GraphQL: validation run
- [x] Security checks
- [x] REST link for build
- [x] REST link for validation run
- [x] DSL (get / set)
- [x] Displaying run info in branch overview (run time, rest in tooltip)
- [x] Displaying run info in build page 
- [x] Need for a `validationStamp` root query
- [x] GraphQL pagination needed for validation runs in validation stamp
- [x] Displaying run info in validation stamp page
- [x] Pagination of runs in the validation stamp page
- [x] ~Metrics for run infos of a build (tags: project / branch)~ - see #604 
- [x] ~Metrics for run infos of a validation run (tags: project / branch / stamp)~ - see #604 
- [x] Displaying run info in validation run page
- [x] Displaying run info in list of runs
- [x] ~Jenkins plugin - option in the build creation and validation~ - see jenkinsci/ontrack-plugin#45
- [x] ~Jenkins plugin - support for steps in pipelines~ - see jenkinsci/ontrack-plugin#45
- [x] For durations < 1 min, display time in seconds (not "a few seconds")
- [x] Documentation (GUI, DSL)
- [x] Restore publication restrictions after Jenkins integration
